// Curated fallback when the user's Spotify library cannot be read
// (e.g. Spotify rate limit). Real Spotify track IDs with real audio
// features, balanced across the four valence/arousal quadrants.
export const DEMO_TRACKS = [
  { spotifyId: "2tTmW7RDtMQtBk7m2rYeSw", title: "Quevedo: Bzrp Music Sessions, Vol. 52", artist: "Bizarrap", valence: 0.55, energy: 0.78, instrumentalness: 0.03, popularity: 99 },
  { spotifyId: "5ww2BF9slyYgNOk37BlC4u", title: "La Bachata", artist: "Manuel Turizo", valence: 0.85, energy: 0.68, instrumentalness: 0.0, popularity: 98 },
  { spotifyId: "4h9wh7iOZ0GGn8QVp4RAOB", title: "I Ain't Worried", artist: "OneRepublic", valence: 0.82, energy: 0.8, instrumentalness: 0.0, popularity: 96 },
  { spotifyId: "4LRPiXqCikLlN15c3yImP7", title: "As It Was", artist: "Harry Styles", valence: 0.66, energy: 0.73, instrumentalness: 0.0, popularity: 95 },
  { spotifyId: "1xzi1Jcr7mEi9K2RfzLOqS", title: "CUFF IT", artist: "Beyoncé", valence: 0.64, energy: 0.69, instrumentalness: 0.0, popularity: 93 },
  { spotifyId: "7dSZ6zGTQx66c2GF91xCrb", title: "PROVENZA", artist: "KAROL G", valence: 0.53, energy: 0.52, instrumentalness: 0.01, popularity: 93 },
  { spotifyId: "0mBP9X2gPCuapvpZ7TGDk3", title: "Left and Right (Feat. Jung Kook of BTS)", artist: "Charlie Puth", valence: 0.72, energy: 0.59, instrumentalness: 0.0, popularity: 92 },
  { spotifyId: "4C6Uex2ILwJi9sZXRdmqXp", title: "Super Freaky Girl", artist: "Nicki Minaj", valence: 0.91, energy: 0.89, instrumentalness: 0.0, popularity: 92 },
  { spotifyId: "3fjN3y5x4hN53rykAN2LHQ", title: "cómo dormiste?", artist: "Rels B", valence: 0.56, energy: 0.43, instrumentalness: 0.0, popularity: 89 },
  { spotifyId: "1JSTJqkT5qHq8MDJnJbRE1", title: "Every Breath You Take", artist: "The Police", valence: 0.74, energy: 0.45, instrumentalness: 0.0, popularity: 86 },
  { spotifyId: "4cktbXiXOapiLBMprHFErI", title: "Memories", artist: "Maroon 5", valence: 0.59, energy: 0.33, instrumentalness: 0.0, popularity: 85 },
  { spotifyId: "2Fxmhks0bxGSBdJ92vM42m", title: "bad guy", artist: "Billie Eilish", valence: 0.56, energy: 0.42, instrumentalness: 0.13, popularity: 84 },
  { spotifyId: "50kpGaPAhYJ3sGmk6vplg0", title: "Love Yourself", artist: "Justin Bieber", valence: 0.52, energy: 0.38, instrumentalness: 0.0, popularity: 84 },
  { spotifyId: "3FAJ6O0NOHQV8Mc5Ri6ENp", title: "Heartbreak Anniversary", artist: "Giveon", valence: 0.54, energy: 0.47, instrumentalness: 0.0, popularity: 84 },
  { spotifyId: "4HBZA5flZLE435QTztThqH", title: "Stuck with U (with Justin Bieber)", artist: "Ariana Grande", valence: 0.54, energy: 0.45, instrumentalness: 0.0, popularity: 83 },
  { spotifyId: "0HaRLPnr887lcQM2YQzkff", title: "For My Hand (feat. Ed Sheeran)", artist: "Burna Boy", valence: 0.72, energy: 0.48, instrumentalness: 0.0, popularity: 83 },
  { spotifyId: "4uUG5RXrOk84mYEfFvj3cK", title: "I'm Good (Blue)", artist: "David Guetta", valence: 0.3, energy: 0.96, instrumentalness: 0.0, popularity: 98 },
  { spotifyId: "6Sq7ltF9Qa7SNFBsV5Cogx", title: "Me Porto Bonito", artist: "Bad Bunny", valence: 0.42, energy: 0.71, instrumentalness: 0.0, popularity: 97 },
  { spotifyId: "1IHWl5LamUGEuP4ozKQSXZ", title: "Tití Me Preguntó", artist: "Bad Bunny", valence: 0.19, energy: 0.71, instrumentalness: 0.0, popularity: 97 },
  { spotifyId: "5IgjP7X4th6nMNDh4akUHb", title: "Under The Influence", artist: "Chris Brown", valence: 0.31, energy: 0.69, instrumentalness: 0.0, popularity: 96 },
  { spotifyId: "3k3NWokhRRkEPhCzPmV8TW", title: "Ojitos Lindos", artist: "Bad Bunny", valence: 0.27, energy: 0.69, instrumentalness: 0.0, popularity: 95 },
  { spotifyId: "6Xom58OOXk2SoU711L2IXO", title: "Moscow Mule", artist: "Bad Bunny", valence: 0.29, energy: 0.67, instrumentalness: 0.0, popularity: 94 },
  { spotifyId: "2QjOHCTQ1Jl3zawyYOpxh6", title: "Sweater Weather", artist: "The Neighbourhood", valence: 0.4, energy: 0.81, instrumentalness: 0.02, popularity: 93 },
  { spotifyId: "3JvKfv6T31zO0ini8iNItO", title: "Another Love", artist: "Tom Odell", valence: 0.13, energy: 0.54, instrumentalness: 0.0, popularity: 93 },
  { spotifyId: "3nqQXoyQOWXiESFLlDF1hG", title: "Unholy (feat. Kim Petras)", artist: "Sam Smith", valence: 0.24, energy: 0.47, instrumentalness: 0.0, popularity: 100 },
  { spotifyId: "5Eax0qFko2dh7Rl2lYs3bx", title: "Efecto", artist: "Bad Bunny", valence: 0.23, energy: 0.47, instrumentalness: 0.0, popularity: 96 },
  { spotifyId: "6xGruZOHLs39ZbVccQTuPZ", title: "Glimpse of Us", artist: "Joji", valence: 0.27, energy: 0.32, instrumentalness: 0.0, popularity: 94 },
  { spotifyId: "31i56LZnwE6uSu3exoHjtB", title: "Neverita", artist: "Bad Bunny", valence: 0.43, energy: 0.5, instrumentalness: 0.0, popularity: 93 },
  { spotifyId: "5XeFesFbtLpXzIVDNQP22n", title: "I Wanna Be Yours", artist: "Arctic Monkeys", valence: 0.48, energy: 0.42, instrumentalness: 0.02, popularity: 92 },
  { spotifyId: "1Fid2jjqsHViMX6xNH70hE", title: "Atlantis", artist: "Seafret", valence: 0.21, energy: 0.48, instrumentalness: 0.0, popularity: 90 },
  { spotifyId: "3WMj8moIAXJhHsyLaqIIHI", title: "Something in the Orange", artist: "Zach Bryan", valence: 0.15, energy: 0.19, instrumentalness: 0.0, popularity: 89 },
  { spotifyId: "0u2P5u6lvoDfwTYjAADbn4", title: "lovely (with Khalid)", artist: "Billie Eilish", valence: 0.12, energy: 0.3, instrumentalness: 0.0, popularity: 89 },
];
